In [8]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import random


# Read the data in, can also use dtype guessing to handle the column memory demanding
# In this case, trun the low_memory = Flase to handle
train_data=pd.read_csv("data/Incidents_Responded_to_by_Fire_Companies.csv",low_memory=False)

# train_data=train_data.drop("Id",1)
train_data.head()

print('Total number of incidents: {}'.format(len(train_data)))

Total number of incidents: 2277779

In [62]:
value = np.array(train_data['INCIDENT_TYPE_DESC'])
import collections
count = collections.Counter(value)
max_count_of_incident = list(count.most_common(1))
a = max_count_of_incident[0][1]/len(train_data)
print('The most common type of incident rate is {}'.format( a ))

The most common type of incident rate is 0.3614828304238471

In [66]:
print('Ratio of 111-building fire to 651 - Smoke scare: {}'.format(count['111 - Building fire']/count['651 - Smoke scare, odor of smoke']))

Ratio of 111-building fire to 651 - Smoke scare: 0.08789046762106846

In [114]:
a = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="710 - Malicious, mischievous false call, other") & (train_data["BOROUGH_DESC"]=="1 - Manhattan") , ["INCIDENT_TYPE_DESC","BOROUGH_DESC"]]
b = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="710 - Malicious, mischievous false call, other") & (train_data["BOROUGH_DESC"]=="3 - Staten Island") , ["INCIDENT_TYPE_DESC","BOROUGH_DESC"]]
print(a.count()/b.count())

INCIDENT_TYPE_DESC    25240
BOROUGH_DESC          25240
dtype: int64
INCIDENT_TYPE_DESC    3.049783
BOROUGH_DESC          3.049783
dtype: float64

In [121]:
train_data['INCIDENT_DATE_TIME'] = pd.to_datetime(train_data['INCIDENT_DATE_TIME'])
#pd.DatetimeIndex(train_data['INCIDENT_DATE_TIME'])

In [124]:
train_data['ARRIVAL_DATE_TIME'] = pd.to_datetime(train_data['ARRIVAL_DATE_TIME'])

                                     INCIDENT_TYPE_DESC   BOROUGH_DESC
52       710 - Malicious, mischievous false call, other  1 - Manhattan
68       710 - Malicious, mischievous false call, other  1 - Manhattan
92       710 - Malicious, mischievous false call, other  1 - Manhattan
101      710 - Malicious, mischievous false call, other  1 - Manhattan
102      710 - Malicious, mischievous false call, other  1 - Manhattan
131      710 - Malicious, mischievous false call, other  1 - Manhattan
163      710 - Malicious, mischievous false call, other  1 - Manhattan
168      710 - Malicious, mischievous false call, other  1 - Manhattan
171      710 - Malicious, mischievous false call, other  1 - Manhattan
174      710 - Malicious, mischievous false call, other  1 - Manhattan
184      710 - Malicious, mischievous false call, other  1 - Manhattan
196      710 - Malicious, mischievous false call, other  1 - Manhattan
197      710 - Malicious, mischievous false call, other  1 - Manhattan
216      710 - Malicious, mischievous false call, other  1 - Manhattan
232      710 - Malicious, mischievous false call, other  1 - Manhattan
282      710 - Malicious, mischievous false call, other  1 - Manhattan
293      710 - Malicious, mischievous false call, other  1 - Manhattan
300      710 - Malicious, mischievous false call, other  1 - Manhattan
310      710 - Malicious, mischievous false call, other  1 - Manhattan
320      710 - Malicious, mischievous false call, other  1 - Manhattan
342      710 - Malicious, mischievous false call, other  1 - Manhattan
455      710 - Malicious, mischievous false call, other  1 - Manhattan
655      710 - Malicious, mischievous false call, other  1 - Manhattan
688      710 - Malicious, mischievous false call, other  1 - Manhattan
737      710 - Malicious, mischievous false call, other  1 - Manhattan
743      710 - Malicious, mischievous false call, other  1 - Manhattan
751      710 - Malicious, mischievous false call, other  1 - Manhattan
1037     710 - Malicious, mischievous false call, other  1 - Manhattan
1100     710 - Malicious, mischievous false call, other  1 - Manhattan
1203     710 - Malicious, mischievous false call, other  1 - Manhattan
...                                                 ...            ...
2273408  710 - Malicious, mischievous false call, other  1 - Manhattan
2273450  710 - Malicious, mischievous false call, other  1 - Manhattan
2273840  710 - Malicious, mischievous false call, other  1 - Manhattan
2274145  710 - Malicious, mischievous false call, other  1 - Manhattan
2274237  710 - Malicious, mischievous false call, other  1 - Manhattan
2274268  710 - Malicious, mischievous false call, other  1 - Manhattan
2274383  710 - Malicious, mischievous false call, other  1 - Manhattan
2274385  710 - Malicious, mischievous false call, other  1 - Manhattan
2274404  710 - Malicious, mischievous false call, other  1 - Manhattan
2274473  710 - Malicious, mischievous false call, other  1 - Manhattan
2274488  710 - Malicious, mischievous false call, other  1 - Manhattan
2274494  710 - Malicious, mischievous false call, other  1 - Manhattan
2274503  710 - Malicious, mischievous false call, other  1 - Manhattan
2274888  710 - Malicious, mischievous false call, other  1 - Manhattan
2274893  710 - Malicious, mischievous false call, other  1 - Manhattan
2274992  710 - Malicious, mischievous false call, other  1 - Manhattan
2275404  710 - Malicious, mischievous false call, other  1 - Manhattan
2275857  710 - Malicious, mischievous false call, other  1 - Manhattan
2275926  710 - Malicious, mischievous false call, other  1 - Manhattan
2276112  710 - Malicious, mischievous false call, other  1 - Manhattan
2276145  710 - Malicious, mischievous false call, other  1 - Manhattan
2276305  710 - Malicious, mischievous false call, other  1 - Manhattan
2276549  710 - Malicious, mischievous false call, other  1 - Manhattan
2276711  710 - Malicious, mischievous false call, other  1 - Manhattan
2276886  710 - Malicious, mischievous false call, other  1 - Manhattan
2277238  710 - Malicious, mischievous false call, other  1 - Manhattan
2277318  710 - Malicious, mischievous false call, other  1 - Manhattan
2277432  710 - Malicious, mischievous false call, other  1 - Manhattan
2277557  710 - Malicious, mischievous false call, other  1 - Manhattan
2277582  710 - Malicious, mischievous false call, other  1 - Manhattan

[25240 rows x 2 columns]

In [128]:
train_data=pd.read_csv("data/Incidents_Responded_to_by_Fire_Companies.csv",low_memory=False)
Building_fire_start = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="111 - Building fire") & (train_data["INCIDENT_DATE_TIME"]) , ["INCIDENT_TYPE_DESC","INCIDENT_DATE_TIME"]]
Building_fire_arrive = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="111 - Building fire") & (train_data["ARRIVAL_DATE_TIME"]) , ["INCIDENT_TYPE_DESC","ARRIVAL_DATE_TIME"]]

In [130]:
Building_fire_start['INCIDENT_DATE_TIME'] = pd.to_datetime(Building_fire_start['INCIDENT_DATE_TIME'])
Building_fire_arrive['ARRIVAL_DATE_TIME'] = pd.to_datetime(Building_fire_arrive['ARRIVAL_DATE_TIME'])

In [138]:
Building_fire_arrive['Time_difference'] = Building_fire_arrive['ARRIVAL_DATE_TIME'] - Building_fire_start['INCIDENT_DATE_TIME']
Building_fire_arrive['Time_difference_second'] = Building_fire_arrive['Time_difference'].dt.total_seconds()

In [144]:
Building_fire_arrive['Time_difference_minutes'] = Building_fire_arrive['Time_difference_second'] / 60.0
print(Building_fire_arrive['Time_difference_minutes'].quantile([0.25,0.5,0.75]))

0.25    2.85
0.50    3.45
0.75    4.15
Name: Time_difference_minutes, dtype: float64

In [186]:
Cooking_fire_and_time = train_data[["INCIDENT_TYPE_DESC" , "INCIDENT_DATE_TIME"]]
Cooking_fire_and_time['INCIDENT_DATE_TIME'] = pd.to_datetime(Cooking_fire_and_time['INCIDENT_DATE_TIME']).dt.hour

C:\Users\Jie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                                        INCIDENT_TYPE_DESC  INCIDENT_DATE_TIME
0                        300 - Rescue, EMS incident, other                   0
1        735A - Unwarranted alarm/defective condition o...                   0
2                        300 - Rescue, EMS incident, other                   0
3                      412 - Gas leak (natural gas or LPG)                   0
4        735A - Unwarranted alarm/defective condition o...                   0
5        735A - Unwarranted alarm/defective condition o...                   0
6         353 - Removal of victim(s) from stalled elevator                   0
7                         651 - Smoke scare, odor of smoke                   0
8                   331 - Lock-in (if lock out , use 511 )                   0
9           710 - Malicious, mischievous false call, other                   0
10                  555 - Defective elevator, no occupants                   0
11       735A - Unwarranted alarm/defective condition o...                   0
12                               522 - Water or steam leak                   0
13                       150 - Outside rubbish fire, other                   0
14                       300 - Rescue, EMS incident, other                   0
15                               522 - Water or steam leak                   0
16       735A - Unwarranted alarm/defective condition o...                   0
17                        651 - Smoke scare, odor of smoke                   0
18                  331 - Lock-in (if lock out , use 511 )                   0
19                        651 - Smoke scare, odor of smoke                   0
20              151 - Outside rubbish, trash or waste fire                   0
21                       300 - Rescue, EMS incident, other                   0
22                        651 - Smoke scare, odor of smoke                   0
23                  118 - Trash or rubbish fire, contained                   0
24              322 - Motor vehicle accident with injuries                   0
25                       300 - Rescue, EMS incident, other                   0
26              151 - Outside rubbish, trash or waste fire                   0
27                       300 - Rescue, EMS incident, other                   0
28        746 - Carbon monoxide detector activation, no CO                   0
29             142 - Brush or brush-and-grass mixture fire                   0
...                                                    ...                 ...
2277749                  300 - Rescue, EMS incident, other                  23
2277750                  300 - Rescue, EMS incident, other                  23
2277751     710 - Malicious, mischievous false call, other                  23
2277752  735A - Unwarranted alarm/defective condition o...                  23
2277753   353 - Removal of victim(s) from stalled elevator                  23
2277754                412 - Gas leak (natural gas or LPG)                  23
2277755                  300 - Rescue, EMS incident, other                  23
2277756   746 - Carbon monoxide detector activation, no CO                  23
2277757          113 - Cooking fire, confined to container                  23
2277758  735A - Unwarranted alarm/defective condition o...                  23
2277759        352 - Extrication of victim(s) from vehicle                  23
2277760                   651 - Smoke scare, odor of smoke                  23
2277761                  300 - Rescue, EMS incident, other                  23
2277762                   651 - Smoke scare, odor of smoke                  23
2277763         740B - Unnecessary alarm/other known cause                  23
2277764                          522 - Water or steam leak                  23
2277765                  300 - Rescue, EMS incident, other                  23
2277766                  300 - Rescue, EMS incident, other                  12
2277767                  300 - Rescue, EMS incident, other                  12
2277768                  300 - Rescue, EMS incident, other                  12
2277769                  300 - Rescue, EMS incident, other                  12
2277770   740A - Unnecessary alarm/construction activities                  12
2277771                  300 - Rescue, EMS incident, other                  12
2277772                  300 - Rescue, EMS incident, other                  12
2277773                  300 - Rescue, EMS incident, other                  12
2277774                  300 - Rescue, EMS incident, other                  12
2277775  735B - Unnecessary alarm/alarm system testing ...                  12
2277776  745A - Unnecessary alarm/ordinary household ac...                  12
2277777  735A - Unwarranted alarm/defective condition o...                  12
2277778  735A - Unwarranted alarm/defective condition o...                  12

[2277779 rows x 2 columns]

In [203]:
Cooking_fire_and_time
#=="113 - Cooking fire, confined to container"
a = Cooking_fire_and_time.loc[Cooking_fire_and_time['INCIDENT_TYPE_DESC'] =="113 - Cooking fire, confined to container"]
group1 = Cooking_fire_and_time.groupby('INCIDENT_DATE_TIME', as_index=False)['INCIDENT_TYPE_DESC'].count()
group1

    INCIDENT_DATE_TIME  INCIDENT_TYPE_DESC
0                    0               71631
1                    1               57394
2                    2               47079
3                    3               41313
4                    4               39658
5                    5               41848
6                    6               52133
7                    7               72671
8                    8               91402
9                    9              102894
10                  10              109463
11                  11              113931
12                  12              117203
13                  13              121908
14                  14              126016
15                  15              126410
16                  16              128304
17                  17              136283
18                  18              133853
19                  19              127787
20                  20              120731
21                  21              110342
22                  22               99051
23                  23               88474

In [216]:
group2 = a.groupby('INCIDENT_DATE_TIME', as_index=False)['INCIDENT_TYPE_DESC'].count()
group2

    INCIDENT_DATE_TIME  INCIDENT_TYPE_DESC
0                    0                2047
1                    1                1571
2                    2                1203
3                    3                1059
4                    4                 951
5                    5                 998
6                    6                1455
7                    7                2007
8                    8                2818
9                    9                3503
10                  10                3983
11                  11                4464
12                  12                5000
13                  13                4963
14                  14                4979
15                  15                5150
16                  16                5680
17                  17                6541
18                  18                6806
19                  19                6456
20                  20                5451
21                  21                4284
22                  22                3140
23                  23                2530

In [219]:
group3 = group2['INCIDENT_TYPE_DESC']/group1['INCIDENT_TYPE_DESC']
print('The highest cooking fire propotion is {}'.format(group3.max()))

The highest cooking fire propotion is 0.050846824501505385

In [328]:
resident_zip_code =pd.read_csv("data/2010+Census+Population+By+Zipcode+(ZCTA).csv",low_memory=False)
resident_zip_code["Zip Code ZCTA"] = resident_zip_code["Zip Code ZCTA"].astype('float')
#resident_zip_code.head()
resident_zip_code = resident_zip_code.rename(columns={"Zip Code ZCTA": "ZIP_CODE"})
zip_incident = train_data.loc[(train_data["INCIDENT_TYPE_DESC"]=="111 - Building fire") & (train_data["ZIP_CODE"]) , ["INCIDENT_TYPE_DESC","ZIP_CODE"]]
zip_incident["ZIP_CODE"] = zip_incident["ZIP_CODE"].astype(float)

population_zip_fire = pd.merge(zip_incident,resident_zip_code,how='inner', on = ['ZIP_CODE'] )

count_fire_with_pop = population_zip_fire.groupby(population_zip_fire['2010 Census Population']).size().reset_index(name='Num. Building fire')
count_fire_with_pop['2010 Census Population']
#zip_incident
#population_zip_fire = train_data.loc[population_zip_fire["Zip Code ZCTA"] == population_zip_fire["ZIP_CODE"] & (population_zip_fire["2010 Census Population"]),["ZIP_CODE","2010 Census Population"]]
#population_zip_fire

0           0
1        1806
2        3011
3        3089
4        4079
5        4534
6        5229
7        6988
8        7135
9        7853
10      11916
11      12281
12      13393
13      13532
14      14016
15      14096
16      15293
17      16575
18      17416
19      17590
20      17823
21      17949
22      18540
23      18556
24      18884
25      19088
26      19168
27      19341
28      20300
29      20408
        ...
142     76174
143     78134
144     78309
145     78731
146     78895
147     79132
148     79492
149     80018
150     81410
151     81677
152     84500
153     85510
154     85871
155     86408
156     86547
157     87757
158     88630
159     89830
160     90117
161     92221
162     93386
163     93877
164     94469
165     94600
166     97060
167     98592
168     99598
169    100820
170    101572
171    109931
Name: 2010 Census Population, Length: 172, dtype: int64

In [334]:
results = {}
coeffs = numpy.polyfit(count_fire_with_pop['2010 Census Population'],count_fire_with_pop['Num. Building fire'],2)
x = count_fire_with_pop['2010 Census Population']
y = count_fire_with_pop['Num. Building fire']
p = numpy.poly1d(coeffs)
# fit values, and mean
yhat = p(x)                         # or [p(z) for z in x]
ybar = numpy.sum(y)/len(y)          # or sum(y)/len(y)
ssreg = numpy.sum((yhat-ybar)**2)   # or sum([ (yihat - ybar)**2 for yihat in yhat])
sstot = numpy.sum((y - ybar)**2)    # or sum([ (yi - ybar)**2 for yi in y])
results['determination'] = ssreg / sstot
print(results['determination'])

0.5943492242479399